files:
  - source: /Project/VikDisk/Resources/Lang/en
    translation: /Project/VikDisk/Resources/Lang/%two_letters_code%/%original_file_name%
  - source: Project/VikDisk/Resources/Lang/en.yaml
    translation: Project/VikDisk/Resources/Lang/%two_letters_code%.yaml
